const products = [
 {id:1,name:'BLUSH CLOUD CARDIGAN',desc:'A soft blush-pink fluffy cardigan',price:289000,type:'cardigan',tag:'SOFT FAVOURITE',img:'assets/asset2.jpg'},
 {id:2,name:'MILKY CLOUD KNIT',desc:'An ivory knit with a cloud-soft feel',price:319000,type:'knit',tag:'EVERYDAY KNIT',img:'assets/asset3.jpg'},
 {id:3,name:'BUTTER BLOOM CARDIGAN',desc:'A butter-yellow cardigan for sunny days',price:299000,type:'cardigan',tag:'A LITTLE SUNSHINE',img:'assets/asset4.jpg'},
 {id:4,name:'MOCHA DAYDREAM KNIT',desc:'An elegant mocha-brown knit',price:319000,type:'knit',tag:'QUIET LUXE',img:'assets/asset5.jpg'},
 {id:5,name:'PEARL SORA CARDIGAN',desc:'A cream cardigan with pearl-style buttons',price:329000,type:'cardigan',tag:'SORA CLASSIC',img:'assets/asset1.jpg'},
 {id:6,name:'ROSE PETAL KNIT',desc:'A lightweight dusty-rose knit',price:279000,type:'knit',tag:'LIGHT LAYER',img:'assets/asset6.jpg'},
 {id:7,name:'VANILLA V-NECK',desc:'A minimal cream V-neck knit',price:299000,type:'knit',tag:'THE ESSENTIAL',img:'assets/asset7.jpg'},
 {id:8,name:'COCOA WRAP CARDIGAN',desc:'A cosy cocoa-brown wrap cardigan',price:339000,type:'cardigan',tag:'COSY DAYS',img:'assets/asset8.jpg'},
 {id:9,name:'CHERRY HEART CARDIGAN',desc:'A sweet cardigan with heart details',price:309000,type:'cardigan',tag:'LOVE NOTE',img:'assets/asset9.jpg'},
 {id:10,name:'IVORY LACE KNIT',desc:'An ivory knit with subtle lace detailing',price:349000,type:'knit',tag:'DELICATE DETAIL',img:'assets/asset10.jpg'},
 {id:11,name:'POLKA MUSE CARDIGAN',desc:'A playful polka knit with a Parisian feel',price:null,type:'cardigan',tag:'THE PARIS EDIT',img:'assets/asset12.jpg'}
];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const rupiah=n=>n==null?'Price soon':'Rp '+n.toLocaleString('id-ID');
let bag=JSON.parse(localStorage.getItem('soraBag')||'[]'),liked=JSON.parse(localStorage.getItem('soraLikes')||'[]'),filter='all';
function sound(kind='click'){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.type='sine';o.frequency.setValueAtTime(kind==='heart'?660:kind==='bag'?740:560,c.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='bag'?1040:kind==='heart'?820:760,c.currentTime+.09);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.035,c.currentTime+.012);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.17);o.start();o.stop(c.currentTime+.18);o.onended=()=>c.close()}catch(e){}}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2300)}
function renderProducts(){let list=[...products],q=$('#searchInput').value.trim().toLowerCase();if(filter!=='all')list=list.filter(p=>p.type===filter);if(q)list=list.filter(p=>(p.name+' '+p.desc+' '+p.tag).toLowerCase().includes(q));const sort=$('#sortSelect').value;if(sort==='low')list.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(sort==='high')list.sort((a,b)=>(b.price??-1)-(a.price??-1));$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.img}" alt="${p.name}" loading="lazy"><span class="product-tag">${p.tag}</span><button class="heart-btn ${liked.includes(p.id)?'liked':''}" data-heart="${p.id}" aria-label="Add ${p.name} to wishlist">${liked.includes(p.id)?'♥':'♡'}</button><button class="quick-btn" data-quick="${p.id}">QUICK VIEW + ADD TO BAG</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.desc}</p></div><span class="product-price">${rupiah(p.price)}</span></div></article>`).join('');$('#noResults').hidden=list.length>0}
function saveBag(){localStorage.setItem('soraBag',JSON.stringify(bag));renderBag()}
function addBag(id){const p=products.find(x=>x.id===id);if(!p)return;if(!p.price){toast('Price for this piece is coming soon ♡');return}const item=bag.find(x=>x.id===id);item?item.qty++:bag.push({id,qty:1});saveBag();sound('bag');toast('Added to your little bag ♡')}
function renderBag(){const count=bag.reduce((s,x)=>s+x.qty,0);$('#bagCount').textContent=`(${count})`;$('#bagItems').innerHTML=bag.length?bag.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="bag-row"><img src="${p.img}" alt="${p.name}"><div><h3>${p.name}</h3><p>${rupiah(p.price)}</p><div class="qty-controls"><button data-qty="${p.id}" data-step="-1" aria-label="Decrease quantity">−</button><span>${x.qty}</span><button data-qty="${p.id}" data-step="1" aria-label="Increase quantity">+</button></div></div><button class="remove-item" data-remove="${p.id}" aria-label="Remove item">×</button></div>`}).join(''):'<p class="empty-bag">Your bag is waiting for something lovely. ♡</p>';$('#subtotal').textContent=rupiah(bag.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0))}
function openBag(){$('#overlay').classList.add('show');$('#bagDrawer').classList.add('open');document.body.style.overflow='hidden'}function closeOverlays(){$('#overlay').classList.remove('show');$('#bagDrawer').classList.remove('open');$('#quickView').classList.remove('show');document.body.style.overflow=''}
function quick(id){const p=products.find(x=>x.id===id);$('#quickContent').innerHTML=`<div class="quick-content"><img src="${p.img}" alt="${p.name}"><div><p class="eyebrow">${p.tag}</p><h2>${p.name}</h2><p>${p.desc}. A thoughtfully picked piece to style with your everyday favourites.</p><div class="price">${rupiah(p.price)}</div><button class="pill-button dark" data-add="${p.id}">ADD TO MY BAG <span>♡</span></button><p>Questions about sizing or styling? Say hello on WhatsApp.</p></div></div>`;$('#quickView').classList.add('show');$('#overlay').classList.add('show');document.body.style.overflow='hidden'}
$('#productGrid').addEventListener('click',e=>{const h=e.target.closest('[data-heart]'),q=e.target.closest('[data-quick]');if(h){const id=+h.dataset.heart;liked=liked.includes(id)?liked.filter(x=>x!==id):[...liked,id];localStorage.setItem('soraLikes',JSON.stringify(liked));sound('heart');renderProducts();toast(liked.includes(id)?'Saved to your lovely list ♡':'Removed from wishlist')}if(q){sound();quick(+q.dataset.quick)}});
$('#quickContent').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b){addBag(+b.dataset.add);if(products.find(p=>p.id===+b.dataset.add)?.price)closeOverlays()}});
$('#bagItems').addEventListener('click',e=>{const q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]');if(q){const id=+q.dataset.qty,step=+q.dataset.step;const item=bag.find(x=>x.id===id);item.qty+=step;if(item.qty<=0)bag=bag.filter(x=>x.id!==id);saveBag();sound()}if(r){bag=bag.filter(x=>x.id!==+r.dataset.remove);saveBag();sound()}});
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.toggle('active',x===b));filter=b.dataset.filter;renderProducts();sound()}));$('#searchInput').addEventListener('input',renderProducts);$('#sortSelect').addEventListener('change',renderProducts);$('#bagOpen').addEventListener('click',()=>{sound();openBag()});$('#bagClose').addEventListener('click',closeOverlays);$('#quickClose').addEventListener('click',closeOverlays);$('#overlay').addEventListener('click',closeOverlays);$('#searchOpen').addEventListener('click',()=>{$('#searchInput').focus();$('#shop').scrollIntoView({behavior:'smooth'});sound()});$('#menuToggle').addEventListener('click',()=>{$('#navLeft').classList.toggle('open');sound()});$$('#navLeft a').forEach(a=>a.addEventListener('click',()=>$('#navLeft').classList.remove('open')));
$('#checkout').addEventListener('click',()=>{if(!bag.length){toast('Your bag is still empty, lovely ♡');return}const lines=bag.map(x=>{const p=products.find(y=>y.id===x.id);return `• ${p.name} x${x.qty} — ${rupiah(p.price*x.qty)}`});const total=bag.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);const msg=`Hi sora.labels! I'd love to order:\n${lines.join('\n')}\n\nSubtotal: ${rupiah(total)}\nCould you help me with availability and shipping? ♡`;window.open('https://wa.me/6285215059711?text='+encodeURIComponent(msg),'_blank','noopener');sound('bag')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlays()});renderProducts();renderBag();
